<a href="https://colab.research.google.com/github/sucheerarighthere/bsc_dpdm22/blob/main/Performace_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Performace Evaluation คือการวัดผล 

In [4]:
from sklearn import datasets
iris_data = datasets.load_iris()

In [5]:
x = iris_data['data']
y= iris_data['target']

### generate code for training decisin tree and evaluate with 10-fold cross validation

In [6]:

from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

# Load the Iris dataset
iris = load_iris()

# Split the dataset into features (X) and target (y)
X = iris.data
y = iris.target

# Create an instance of the DecisionTreeClassifier class
clf = DecisionTreeClassifier()

# Perform 10-fold cross-validation and compute the mean accuracy
scores = cross_val_score(clf, X, y, cv=10)
mean_accuracy = scores.mean()

# Print the mean accuracy
print("Mean accuracy:", mean_accuracy)

Mean accuracy: 0.96


In [7]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

# Load the Iris dataset
iris = load_iris()

# Split the dataset into features (X) and target (y)
X = iris.data
y = iris.target

# Create an instance of the DecisionTreeClassifier class
clf = DecisionTreeClassifier(max_depth=2)

# Perform 10-fold cross-validation and compute the mean accuracy
scores = cross_val_score(clf, X, y, cv=10)
mean_accuracy = scores.mean()

# Print the mean accuracy
print("Mean accuracy:", mean_accuracy)

Mean accuracy: 0.9466666666666667


อันนี้มีการสรุป std

In [8]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import LeaveOneOut, cross_val_score

# Load the iris dataset
iris = load_iris()

# Split the data into features (X) and labels (y)
X = iris.data
y = iris.target

# Create an instance of the decision tree classifier
clf = DecisionTreeClassifier()

# Create a leave-one-out cross-validation object
loo = LeaveOneOut()

# Evaluate the decision tree classifier using leave-one-out cross-validation
scores = cross_val_score(clf, X, y, cv=loo)

# Compute the mean accuracy and standard deviation and print them out
mean_accuracy = scores.mean()
std_dev = scores.std()
print("Mean accuracy:", mean_accuracy)
print("Standard deviation:", std_dev)

Mean accuracy: 0.9466666666666667
Standard deviation: 0.2246973272847029


In [9]:
from sklearn.datasets import load_iris
from sklearn.model_selection import LeaveOneOut, cross_val_score
from sklearn.tree import DecisionTreeClassifier

# Load the Iris dataset
iris = load_iris()

# Split the dataset into features (X) and target (y)
X = iris.data
y = iris.target

# Create an instance of the DecisionTreeClassifier class
clf = DecisionTreeClassifier()

# Create an instance of the LeaveOneOut class
loo = LeaveOneOut()

# Perform leave-one-out cross-validation and compute the mean accuracy
scores = cross_val_score(clf, X, y, cv=loo)
mean_accuracy = scores.mean()

# Print the mean accuracy
print("Mean accuracy:", mean_accuracy)

Mean accuracy: 0.9466666666666667


# วิธียาก

transform numpy to data frame with column name 

In [10]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
import pandas as pd

In [12]:
columns=iris_data['feature_names']
x_df = pd.DataFrame(X,columns=columns)

In [13]:
x_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

### ขั้นตอนแบ่งfold >> shuffle ข้อมูล

In [14]:
x_df['label']=y #เพิ่มคอลัมน์ก่อน ค่อยชัฟเฟิล
x_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [15]:
shuffle = x_df.sample(frac=1)
shuffle
#แต่การสลับindex ต้องสลับ คำตอบด้วย
#มี column ที่บอกข้อมูลแล้ว เราสามารถ 

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
31                 5.4               3.4                1.5               0.4   
120                6.9               3.2                5.7               2.3   
47                 4.6               3.2                1.4               0.2   
25                 5.0               3.0                1.6               0.2   
75                 6.6               3.0                4.4               1.4   
..                 ...               ...                ...               ...   
16                 5.4               3.9                1.3               0.4   
123                6.3               2.7                4.9               1.8   
63                 6.1               2.9                4.7               1.4   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   

     label  
31       0  
120      2  
47       0  
25       0  
75       1  
..     ...  
16       0  
123      2  
63       1  
3        0  
4        0  

[150 rows x 5 columns]

In [16]:
shuffle['fold']=15*[1,2,3,4,5,6,7,8,9,10]
shuffle

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
31                 5.4               3.4                1.5               0.4   
120                6.9               3.2                5.7               2.3   
47                 4.6               3.2                1.4               0.2   
25                 5.0               3.0                1.6               0.2   
75                 6.6               3.0                4.4               1.4   
..                 ...               ...                ...               ...   
16                 5.4               3.9                1.3               0.4   
123                6.3               2.7                4.9               1.8   
63                 6.1               2.9                4.7               1.4   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   

     label  fold  
31       0     1  
120      2     2  
47       0     3  
25       0     4  
75       1     5  
..     ...   ...  
16       0     6  
123      2     7  
63       1     8  
3        0     9  
4        0    10  

[150 rows x 6 columns]

HW -10 fold รอบที่1 อันแรก test ที่เหลือ train วัดผลด้วยdata คาบที่แล้ว 

In [17]:
shuffle.sort_values('fold')

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
31                 5.4               3.4                1.5               0.4   
61                 5.9               3.0                4.2               1.5   
101                5.8               2.7                5.1               1.9   
128                6.4               2.8                5.6               2.1   
136                6.3               3.4                5.6               2.4   
..                 ...               ...                ...               ...   
84                 5.4               3.0                4.5               1.5   
88                 5.6               3.0                4.1               1.3   
142                5.8               2.7                5.1               1.9   
51                 6.4               3.2                4.5               1.5   
4                  5.0               3.6                1.4               0.2   

     label  fold  
31       0     1  
61       1     1  
101      2     1  
128      2     1  
136      2     1  
..     ...   ...  
84       1    10  
88       1    10  
142      2    10  
51       1    10  
4        0    10  

[150 rows x 6 columns]

In [18]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [19]:
## Define feature names
feature_names = iris_data.feature_names

# Define target names
target_names = iris_data.target_names

# Define Decision Tree Classifier
clf = DecisionTreeClassifier()

# Define KFold with 10 folds
kf = KFold(n_splits=10, shuffle=True, random_state=6)

# Initialize lists to store results
accuracies = []
feature_importances = []

# Loop through each fold
for fold, (train_index, test_index) in enumerate(kf.split(iris_data.data)):
    
    # Get train and test data
    X_train, X_test = iris_data.data[train_index], iris_data.data[test_index]
    y_train, y_test = iris_data.target[train_index], iris_data.target[test_index]
    
    # Fit classifier on training data
    clf.fit(X_train, y_train)
    
    # Make predictions on test data
    y_pred = clf.predict(X_test)
    
    # Calculate accuracy score
    accuracy = accuracy_score(y_test, y_pred)
    
    # Store accuracy score in list
    accuracies.append(accuracy)
    
    # Get feature importances
    feature_importance = clf.feature_importances_
    
    # Store feature importances in list
    feature_importances.append(feature_importance)

    # Create a DataFrame to display the iris data for each fold
    iris_data1 = np.concatenate((X_test, y_test.reshape(-1,1)), axis=1)
    columns = iris_data['feature_names']
    X_df = pd.DataFrame(data=iris_data1, columns=columns+['label'])
    X_df['label'] = y_test
    df = X_df.sample(frac=1, random_state=6)
    df['fold'] = fold+1

    # Print fold number and accuracy score
    print(f"Fold {fold+1}")
    print("Cross-validation accuracy: %0.2f (+/- %0.2f)" % (np.mean(accuracies), np.std(accuracies) * 2))
    
    # Show sample of data for current fold
    print(df)
    
    print("\n")

Fold 1
Cross-validation accuracy: 1.00 (+/- 0.00)
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
11                6.1               3.0                4.9               1.8   
13                7.7               3.0                6.1               2.3   
6                 5.5               2.4                3.7               1.0   
7                 5.7               2.9                4.2               1.3   
2                 5.1               3.3                1.7               0.5   
8                 6.4               3.2                5.3               2.3   
5                 6.4               2.9                4.3               1.3   
12                6.1               2.6                5.6               1.4   
1                 5.0               3.6                1.4               0.2   
0                 4.7               3.2                1.3               0.2   
14                6.4               3.1                5.5            

# 24 feb 2023

In [21]:
#with confusiopn matrix
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, cross_val_predict
from sklearn.metrics import confusion_matrix
import numpy as np

# Load iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create decision tree classifier
dtc = DecisionTreeClassifier()

# Perform 10-fold cross-validation on the training set
y_pred = cross_val_predict(dtc, X_train, y_train, cv=10)

# Fit the classifier on the training set
dtc.fit(X_train, y_train)

# Predict the labels of the test set
y_pred_test = dtc.predict(X_test)

# Generate confusion matrix for the test set
cm = confusion_matrix(y_test, y_pred_test)

# Generate confusion matrix for the training set
cm_train = confusion_matrix(y_train, y_pred)

# Print results
print("Confusion matrix for training set:")
print(cm_train)
print("Confusion matrix for test set:")
print(cm)

Confusion matrix for training set:
[[31  0  0]
 [ 0 33  4]
 [ 0  3 34]]
Confusion matrix for test set:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


# key from al.tohn

In [22]:
shuffle

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
31                 5.4               3.4                1.5               0.4   
120                6.9               3.2                5.7               2.3   
47                 4.6               3.2                1.4               0.2   
25                 5.0               3.0                1.6               0.2   
75                 6.6               3.0                4.4               1.4   
..                 ...               ...                ...               ...   
16                 5.4               3.9                1.3               0.4   
123                6.3               2.7                4.9               1.8   
63                 6.1               2.9                4.7               1.4   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   

     label  fold  
31       0     1  
120      2     2  
47       0     3  
25       0     4  
75       1     5  
..     ...   ...  
16       0     6  
123      2     7  
63       1     8  
3        0     9  
4        0    10  

[150 rows x 6 columns]

In [56]:
test_fold = 1 #เอาfold 1 มาเป็นtest #พยายามใช้ ชื่อให้ตรง
test_data = shuffle[shuffle['fold']==test_fold] #define test data
training_data = shuffle[shuffle['fold']!=test_fold] #define traning data

In [29]:
test_data #ดูหน้าตา สองคอลัมน์สุดท้ายไม่เอา มันเปนโฟล 

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
31                 5.4               3.4                1.5               0.4   
96                 5.7               2.9                4.2               1.3   
30                 4.8               3.1                1.6               0.2   
46                 5.1               3.8                1.6               0.2   
143                6.8               3.2                5.9               2.3   
128                6.4               2.8                5.6               2.1   
61                 5.9               3.0                4.2               1.5   
39                 5.1               3.4                1.5               0.2   
101                5.8               2.7                5.1               1.9   
136                6.3               3.4                5.6               2.4   
42                 4.4               3.2                1.3               0.2   
54                 6.5               2.8                4.6               1.5   
57                 4.9               2.4                3.3               1.0   
8                  4.4               2.9                1.4               0.2   
132                6.4               2.8                5.6               2.2   

     label  fold  
31       0     1  
96       1     1  
30       0     1  
46       0     1  
143      2     1  
128      2     1  
61       1     1  
39       0     1  
101      2     1  
136      2     1  
42       0     1  
54       1     1  
57       1     1  
8        0     1  
132      2     1

In [55]:
X_test = test_data.iloc[:,:-2] #เอาทุกอันยกเว้นสองคอลลัมน์สุดท้าย
Y_test =  test_data.iloc[:,-2] #เอาแค่สองคอลสุดท้าย
X_train =training_data.iloc[:,:-2]
Y_train =training_data.iloc[:,-2]

In [63]:
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [53]:
model = DecisionTreeClassifier(max_depth=2) #define
model.fit(X_train,Y_train) #train
y_predict = model.predict(X_test) #predict

In [54]:
acc = accuracy_score(Y_test,y_predict)
print(f'accuracy of fold {test_fold}={acc}')


accuracy of fold 1=1.0


In [65]:
acc_fold=[]
for test_fold in range(1,11):
  test_data = shuffle[shuffle['fold']==test_fold] #define test data
  training_data = shuffle[shuffle['fold']!=test_fold] #define traning data

  X_test = test_data.iloc[:,:-2] #เอาทุกอันยกเว้นสองคอลลัมน์สุดท้าย
  Y_test =  test_data.iloc[:,-2]
  X_train =training_data.iloc[:,:-2]
  Y_train =training_data.iloc[:,-2]

  model = DecisionTreeClassifier(max_depth=2) #define
  model.fit(X_train,Y_train) #train
  y_predict = model.predict(X_test) #predict

  acc = accuracy_score(Y_test,y_predict)
  print(f'accuracy of fold {test_fold}={acc}')
  acc_fold.append(acc)
#ปกติเราไม่ไรด้หยุดแค่นี้ปกติเราก็เอาเลขไปใช้ต่อ อย่าลืมสร้างลิสต์มาเก็บ 
#จบแบบสวยๆ ปริ้นค่าเฉลี่ยด้วย
print (f'\naverage accuracy = {np.mean(acc)}')

accuracy of fold 1=1.0
accuracy of fold 2=0.9333333333333333
accuracy of fold 3=0.9333333333333333
accuracy of fold 4=1.0
accuracy of fold 5=0.8666666666666667
accuracy of fold 6=0.9333333333333333
accuracy of fold 7=0.9333333333333333
accuracy of fold 8=1.0
accuracy of fold 9=0.8
accuracy of fold 10=0.9333333333333333

average accuracy = 0.9333333333333333
